# SPDX-License-Identifier: MIT-0
---
- name: Ensure target directory exists
  ansible.builtin.file:
    path: /srv/tradeoffer
    state: directory
    mode: '0755'

- name: Clone repository
  ansible.builtin.git:
    repo: https://github.com/Alex-Sing-bit/Docker
    dest: /srv/tradeoffer
    version: main
    force: yes
    update: yes  

- name: Install docker-compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Start Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /srv/tradeoffer
    state: present
    pull: missing
    build: yes
    recreate: always
    wait: yes
    wait_timeout: 300
  register: compose_start
  async: 60
  poll: 0

- name: Check containers status
  community.docker.docker_compose_v2:
    project_src: /srv/tradeoffer
  register: containers_status
  delegate_to: "{{ inventory_hostname }}"

- name: Wait for backend to become ready
  ansible.builtin.uri:
    url: "http://127.0.0.1:3001"  # Изменено с localhost на 127.0.0.1
    method: GET
    status_code: 200
    timeout: 30
  register: health_check
  until: health_check.status == 200
  retries: 20  # Увеличено количество попыток
  delay: 10
  ignore_errors: yes
  delegate_to: "{{ inventory_hostname }}"  # Важно: выполняем проверку на целевой машине

- name: Fail if application not ready
  ansible.builtin.fail:
    msg: "Application failed to start after 150 seconds"
  when: health_check.status != 200

- name: Get backend logs
  ansible.builtin.command: docker logs tradeoffer-backend-1
  register: backend_logs
  ignore_errors: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Show backend logs
  ansible.builtin.debug:
    var: backend_logs.stdout_lines